# Generated by Django 2.2.2 on 2019-06-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='title1',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
