# Generated by Django 2.2.2 on 2019-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20190616_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('query', models.CharField(max_length=100, verbose_name='Query')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
